//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Address
    {
        public int addressID { get; set; }
        public int userID { get; set; }
        [Required]
        [Display(Name = "Province")]
        public string province { get; set; }
        [Required]
        [Display(Name = "City")]
        public string city { get; set; }
        [Required]
        [Display(Name = "Address")]
        public string address1 { get; set; }
        [Required]
        [Display(Name = "Is Default Address")]
        public int isDefault { get; set; }
        [Required]
        [Display(Name = "Created At")]
        public System.DateTime createdDate { get; set; }
        [Required]
        [Display(Name = "Updated At")]
        public System.DateTime updatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
