//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Platform
    {
        public int platformID { get; set; }
        [Display(Name = "Platform")]
        [Required]
        public string platformName { get; set; }
        [Display(Name = "Created At")]
        public Nullable<System.DateTime> createdDate { get; set; }
        [Display(Name = "Updated At")]
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
